services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: benchmarkdb
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  benchmark:
    build: .
    depends_on:
      - postgres
      - elasticsearch
